name: Provision EC2

on: workflow_dispatch

jobs:
  runterraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List out directory
        run: ls

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
        


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Terraform init
        run: terraform init -upgrade 


      - name: Terraform apply
        id: terraform
        run: terraform apply -auto-approve


      - name: Output Instance Public IP
        id: ip
        run: |
          IP=$(terraform output -raw instance_public_ip)
          echo PUBLIC_IP=$IP >> $GITHUB_OUTPUT
          echo "The public IP is $IP"
    outputs:
      public_ip: ${{ steps.ip.outputs.PUBLIC_IP }}


  install-ansible:
    needs: runterraform  # Make this job depend on the `terraform` job
    runs-on: ubuntu-latest
    steps:

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use the IP
        run: |
          echo "The public IP from the terraform job is ${{ needs.runterraform.outputs.public_ip }}"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Ansible
        run: python -m pip install --upgrade pip && pip install ansible

      - name: Create Ansible Inventory
        run: |
          echo '[ec2_instance]' > inventory
          echo '${{ needs.runterraform.outputs.public_ip }}' >> inventory
          cat inventory

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory playbook.yml
          ssh -o StrictHostKeyChecking=no  ${{ secrets.EC2_USER }}@${{ needs.runterraform.outputs.public_ip }} "echo 'hello world'"
          ssh -o StrictHostKeyChecking=no  ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'hello world 2'"

        env:
          ANSIBLE_HOST_KEY_CHECKING: False
  # deployAnsible:
  #   needs: install-ansible
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: ./
  #       with: 
  #         playbook: playbook.yml
  #         inventory: inventory
  